name: Time Tracker

on:
  push:
  issue_comment:
  pull_request:
    types:
      - opened
      - closed
      - edited

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Track Time
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update PR Title
        uses: dcasia/git-time-tacker
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          durationPattern: 'h:mm'
          titlePattern: '[:duration] capitalize(:title)'
